# ==========================================
# Component:   Backend Service (NodePort)
# ==========================================

apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    tier: api
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8001        # Internal Cluster Port
      targetPort: 80    # Application Port inside Container
      nodePort: 30001   # External Port for Access
