# ==========================================
# Component:   Frontend Service (NodePort)
# ==========================================

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    tier: ui
spec:
  type: NodePort
  selector:
    app: frontend  # Deployment ke matchLabels se match hona chahiye
  ports:
    - name: http
      protocol: TCP
      port: 80          # Port inside the cluster
      targetPort: 80    # Port on the container
      nodePort: 30080   # External port for browser access
