# ==========================================
# Component:   Redis Service (Internal)
# ==========================================

apiVersion: v1
kind: Service
metadata:
  name: redis # Yehi naam Backend ki env mein REDIS_HOST ki jagah use ho raha hai
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
